

export const RECEIVE_SIZE='RECEIVE_SIZE';
export const RECEIVE_PRODUCTS='RECEIVE_PRODUCTS';
export const SHOW_CART='SHOW_CART';
export const BUY_PRODUCT_BUY_ID='BUY_PRODUCT_BUY_ID';
export const ADD_TO_CART='ADD_TO_CART';
export const SELECT='SELECT';
export const HIGHEST_TO_LOWEST='HIGHEST_TO_LOWEST';
export const LOWEST_TO_HIGHEST='LOWEST_TO_HIGHEST';
export const SELECT_TYPE='SELECT_TYPE';
export const SELECT_SIZE='SELECT_SIZE';
